import { Router } from 'express'; import bcrypt from 'bcryptjs'; import QRCode from 'qrcode'; import { z } from 'zod'; import { query } from '../db'; import { auth,permit } from '../middleware/auth'; import { config } from '../config'; import { AuthRequest } from '../types';
export const adminRouter=Router(); adminRouter.use(auth,permit('admin'));
const resources:any={categories:{table:'categories',fields:['name','description','sort_order','active']},menu:{table:'menu_items',fields:['category_id','name','description','price','image_url','food_type','available']},tables:{table:'restaurant_tables',fields:['name','capacity','active']}};
for(const [path,r] of Object.entries<any>(resources)){
 adminRouter.get(`/${path}`,async(req:AuthRequest,res,next)=>{try{const x=await query(`SELECT * FROM ${r.table} WHERE branch_id=$1 ORDER BY created_at DESC`,[req.staff!.branchId]);res.json(x.rows)}catch(e){next(e)}});
 adminRouter.post(`/${path}`,async(req:AuthRequest,res,next)=>{try{const fields=r.fields.filter((f:string)=>req.body[f]!==undefined);const vals=fields.map((f:string)=>req.body[f]);const x=await query(`INSERT INTO ${r.table}(branch_id,${fields.join(',')}) VALUES($1,${fields.map((_:any,i:number)=>`$${i+2}`).join(',')}) RETURNING *`,[req.staff!.branchId,...vals]);res.status(201).json(x.rows[0])}catch(e){next(e)}});
 adminRouter.patch(`/${path}/:id`,async(req:AuthRequest,res,next)=>{try{const fields=r.fields.filter((f:string)=>req.body[f]!==undefined);if(!fields.length)return res.status(400).json({message:'No changes'});const vals=fields.map((f:string)=>req.body[f]);const x=await query(`UPDATE ${r.table} SET ${fields.map((f:string,i:number)=>`${f}=$${i+1}`).join(',')}${r.table==='menu_items'?',updated_at=now()':''} WHERE id=$${fields.length+1} AND branch_id=$${fields.length+2} RETURNING *`,[...vals,req.params.id,req.staff!.branchId]);res.json(x.rows[0])}catch(e){next(e)}});
 adminRouter.delete(`/${path}/:id`,async(req:AuthRequest,res,next)=>{try{await query(`DELETE FROM ${r.table} WHERE id=$1 AND branch_id=$2`,[req.params.id,req.staff!.branchId]);res.status(204).end()}catch(e){next(e)}});
}
adminRouter.get('/branches',async(req:AuthRequest,res,next)=>{try{res.json((await query('SELECT id,name,slug,address,phone,gst_number,gst_percent,active FROM branches ORDER BY name')).rows)}catch(e){next(e)}});
adminRouter.patch('/branches/:id',async(req:AuthRequest,res,next)=>{try{const p=z.object({name:z.string().optional(),address:z.string().optional(),phone:z.string().optional(),gst_number:z.string().optional(),gst_percent:z.number().min(0).max(100).optional(),razorpay_key_id:z.string().optional(),razorpay_key_secret:z.string().optional()}).parse(req.body);const fields=Object.keys(p),vals=Object.values(p);const r=await query(`UPDATE branches SET ${fields.map((f,i)=>`${f}=$${i+1}`).join(',')},updated_at=now() WHERE id=$${fields.length+1} RETURNING id,name,slug,address,phone,gst_number,gst_percent,active`,[...vals,req.params.id]);res.json(r.rows[0])}catch(e){next(e)}});
adminRouter.get('/staff',async(req:AuthRequest,res,next)=>{try{res.json((await query('SELECT id,name,email,role,active,created_at FROM users WHERE branch_id=$1 ORDER BY created_at DESC',[req.staff!.branchId])).rows)}catch(e){next(e)}});
adminRouter.post('/staff',async(req:AuthRequest,res,next)=>{try{const p=z.object({name:z.string(),email:z.string().email(),password:z.string().min(6),role:z.enum(['operator','kitchen'])}).parse(req.body);const hash=await bcrypt.hash(p.password,12);const r=await query('INSERT INTO users(branch_id,name,email,password_hash,role) VALUES($1,$2,$3,$4,$5) RETURNING id,name,email,role,active',[req.staff!.branchId,p.name,p.email,hash,p.role]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
adminRouter.patch('/staff/:id',async(req:AuthRequest,res,next)=>{try{const active=Boolean(req.body.active);const r=await query("UPDATE users SET active=$1,updated_at=now() WHERE id=$2 AND branch_id=$3 AND role!='admin' RETURNING id,name,email,role,active",[active,req.params.id,req.staff!.branchId]);res.json(r.rows[0])}catch(e){next(e)}});
adminRouter.get('/tables/:id/qr',async(req:AuthRequest,res,next)=>{try{const r=await query('SELECT qr_token FROM restaurant_tables WHERE id=$1 AND branch_id=$2',[req.params.id,req.staff!.branchId]);if(!r.rows[0])return res.status(404).end();const png=await QRCode.toBuffer(`${config.PUBLIC_APP_URL}/menu/${r.rows[0].qr_token}`,{width:900,margin:2,color:{dark:'#21160f',light:'#fffaf0'}});res.type('png').attachment(`table-${req.params.id}-qr.png`).send(png)}catch(e){next(e)}});
