'use client';

import { useEffect, useMemo, useState } from 'react';
import { Check, ChevronRight, Minus, Plus, ShoppingBag, Sparkles, StickyNote, X } from 'lucide-react';
import { API, api, money } from '@/lib/api';

type Item={id:string;name:string;description:string;price:string;image_url:string;food_type:string};
type Cart=Record<string,{item:Item;qty:number;note?:string}>;

export default function Menu({params}:{params:{token:string}}){
  const [data,setData]=useState<any>();const [cart,setCart]=useState<Cart>({});const [cartOpen,setCartOpen]=useState(false);const [selected,setSelected]=useState<Item|null>(null);const [order,setOrder]=useState<any>();const [payment,setPayment]=useState<'cash'|'upi'>('cash');const [error,setError]=useState('');const [customerName,setCustomerName]=useState('');const [customerPhone,setCustomerPhone]=useState('');const [orderNote,setOrderNote]=useState('');
  useEffect(()=>{const refresh=()=>api(`/api/public/menu/${params.token}`).then(next=>{setData(next);const available=new Set(next.categories.flatMap((category:any)=>category.items.map((item:any)=>item.id)));setCart(current=>{const kept=Object.fromEntries(Object.entries(current).filter(([id])=>available.has(id)));if(Object.keys(kept).length<Object.keys(current).length)setError('A sold-out item was removed from your cart.');return kept})}).catch(e=>setError(e.message));refresh();const timer=setInterval(refresh,20000);return()=>clearInterval(timer)},[params.token]);
  useEffect(()=>{if(!order?.id||['served','cancelled'].includes(order.status))return;const timer=setInterval(()=>api(`/api/public/orders/${order.id}`).then(setOrder),5000);return()=>clearInterval(timer)},[order]);
  const subtotal=useMemo(()=>Object.values(cart).reduce((sum,line)=>sum+Number(line.item.price)*line.qty,0),[cart]);const quantity=Object.values(cart).reduce((sum,line)=>sum+line.qty,0);const gst=Number(data?.table?.gst_percent||5);const total=subtotal*(1+gst/100);
  function changeQuantity(item:Item,delta:number){setCart(current=>{const next={...current},existing=next[item.id],count=(existing?.qty||0)+delta;if(count<=0)delete next[item.id];else next[item.id]={item,qty:count,note:existing?.note};return next})}
  function addConfigured(item:Item,qty:number,note:string){setCart(current=>{const existing=current[item.id];return{...current,[item.id]:{item,qty:(existing?.qty||0)+qty,note:note||existing?.note}}});setSelected(null)}
  function updateNote(id:string,note:string){setCart(current=>({...current,[id]:{...current[id],note}}))}

  async function checkout(){const cartBeforePayment={...cart};try{setError('');const result:any=await api('/api/public/orders',{method:'POST',body:JSON.stringify({tableToken:params.token,paymentMethod:payment,customerName:customerName||undefined,customerPhone:customerPhone||undefined,notes:orderNote||undefined,items:Object.values(cart).map(line=>({menuItemId:line.item.id,quantity:line.qty,specialInstructions:line.note||undefined}))})});if(payment!=='upi'||!result.razorpay){setOrder(result.order);setCart({});setCartOpen(false);return}const Razorpay=(window as any).Razorpay;if(!Razorpay)throw new Error('Payment service is loading. Please retry.');let completed=false;const rollback=async(message:string)=>{if(completed)return;completed=true;await api(`/api/public/orders/${result.id}/payment-failed`,{method:'POST',body:'{}'}).catch(()=>undefined);setCart(cartBeforePayment);setCartOpen(true);setError(message)};const gateway=new Razorpay({key:result.keyId,amount:result.razorpay.amount,currency:'INR',name:'Indian Kitchen',order_id:result.razorpay.id,method:{upi:true,card:false},prefill:{name:customerName,contact:customerPhone},handler:async(response:any)=>{try{const paid=await api(`/api/public/orders/${result.id}/verify-payment`,{method:'POST',body:JSON.stringify(response)});completed=true;setOrder(paid);setCart({});setCartOpen(false)}catch(e:any){await rollback(e.message||'Payment verification failed. Your cart has been restored.')}},modal:{ondismiss:()=>rollback('Payment cancelled. Your cart has been restored.')}});gateway.on('payment.failed',()=>rollback('Payment failed. Nothing was sent to the kitchen; your cart is ready to retry.'));gateway.open()}catch(e:any){setCart(cartBeforePayment);setCartOpen(true);setError(e.message)}}

  if(error&&!data)return <div className="center">{error}</div>;if(!data)return <div className="center">Preparing the menu…</div>;
  if(order)return <OrderTracking order={order} back={()=>setOrder(null)}/>;
  return <main className="menuPage"><script src="https://checkout.razorpay.com/v1/checkout.js"/><header className="menuHero"><div className="menuOverlay"/><div><p className="eyebrow">{data.table.branch_name}</p><h1>Good food.<br/><em>No hurry.</em></h1><p>{data.table.name} · {data.table.address}</p></div></header><div className="categoryNav">{data.categories.map((category:any)=><a key={category.id} href={`#c-${category.id}`}>{category.name}</a>)}</div><div className="menuContent">{data.categories.map((category:any)=><section id={`c-${category.id}`} key={category.id}><p className="eyebrow red">Explore</p><h2>{category.name}</h2><p className="sectionDesc">{category.description}</p><div className="menuGrid">{category.items.map((item:Item)=><article className="menuCard" key={item.id}><button className="foodImg" onClick={()=>setSelected(item)} style={{backgroundImage:`url(${item.image_url})`}}><span className={item.food_type}>{item.food_type==='veg'?'Veg':'Non-veg'}</span><i>View details <ChevronRight/></i></button><div className="foodBody"><h3>{item.name}</h3><p>{item.description}</p><div><b>{money(item.price)}</b><button onClick={()=>setSelected(item)}>{cart[item.id]?<>{cart[item.id].qty} in cart <Plus/></>:<>Add <Plus/></>}</button></div></div></article>)}</div></section>)}</div>{quantity>0&&<button className="cartBar" onClick={()=>setCartOpen(true)}><span><ShoppingBag/> {quantity} item{quantity>1?'s':''}</span><b>{money(subtotal)} · View cart</b></button>}{selected&&<DishDetail item={selected} existing={cart[selected.id]?.qty||0} close={()=>setSelected(null)} add={addConfigured}/>} {cartOpen&&<CartDrawer cart={cart} close={()=>setCartOpen(false)} change={changeQuantity} updateNote={updateNote} subtotal={subtotal} gst={gst} total={total} payment={payment} setPayment={setPayment} checkout={checkout} error={error} customerName={customerName} customerPhone={customerPhone} orderNote={orderNote} setCustomerName={setCustomerName} setCustomerPhone={setCustomerPhone} setOrderNote={setOrderNote}/>}</main>;
}

function DishDetail({item,existing,close,add}:{item:Item;existing:number;close:()=>void;add:(item:Item,qty:number,note:string)=>void}){const[qty,setQty]=useState(1),[note,setNote]=useState('');return <div className="dishDetail"><div onClick={close}/><article><button className="detailClose" onClick={close}><X/></button><div className="detailImage" style={{backgroundImage:`url(${item.image_url})`}}><span className={item.food_type}>{item.food_type==='veg'?'Vegetarian':'Non-vegetarian'}</span></div><section><p className="eyebrow red">From our kitchen</p><h2>{item.name}</h2><p>{item.description}</p><div className="detailPrice"><b>{money(item.price)}</b><span>Inclusive of applicable taxes</span></div><label><StickyNote/> Special instruction<textarea value={note} onChange={event=>setNote(event.target.value)} maxLength={300} placeholder="Less spicy, no onion, allergy note…"/></label><div className="detailAction"><div><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus/></button><b>{qty}</b><button onClick={()=>setQty(qty+1)}><Plus/></button></div><button onClick={()=>add(item,qty,note)}>Add {qty} · {money(Number(item.price)*qty)}</button></div>{existing>0&&<small><Check/> {existing} already in your cart</small>}</section></article></div>}

function CartDrawer(props:any){const{cart,close,change,updateNote,subtotal,gst,total,payment,setPayment,checkout,error,customerName,customerPhone,orderNote,setCustomerName,setCustomerPhone,setOrderNote}=props;return <div className="drawer"><div className="backdrop" onClick={close}/><aside className="richCart"><button className="close" onClick={close}><X/></button><p className="eyebrow red">Your table</p><h2>Review your order.</h2><div className="cartLines">{Object.values(cart).map((raw:any)=>{const line=raw as Cart[string];return <div className="richCartItem" key={line.item.id}><img src={line.item.image_url} alt=""/><div><b>{line.item.name}</b><span>{money(line.item.price)}</span><textarea value={line.note||''} onChange={event=>updateNote(line.item.id,event.target.value)} placeholder="Add special instruction…"/></div><div><button onClick={()=>change(line.item,-1)}><Minus/></button><b>{line.qty}</b><button onClick={()=>change(line.item,1)}><Plus/></button></div></div>})}</div><section className="guestForm"><h3>Your details <span>Optional</span></h3><div><input value={customerName} onChange={event=>setCustomerName(event.target.value)} placeholder="Your name" maxLength={120}/><input value={customerPhone} onChange={event=>setCustomerPhone(event.target.value)} placeholder="Phone number" maxLength={30}/></div><textarea value={orderNote} onChange={event=>setOrderNote(event.target.value)} placeholder="Note for the complete order…" maxLength={500}/></section><div className="payment"><h3>Choose payment</h3><label><input type="radio" checked={payment==='cash'} onChange={()=>setPayment('cash')}/><span><b>Cash at counter</b><small>Pay to our operator after ordering</small></span></label><label><input type="radio" checked={payment==='upi'} onChange={()=>setPayment('upi')}/><span><b>Pay securely by UPI</b><small>Razorpay verified payment</small></span></label></div><div className="cartTotals"><div><span>Subtotal</span><b>{money(subtotal)}</b></div><div><span>GST ({gst}%)</span><b>{money(total-subtotal)}</b></div><div><span>Total</span><b>{money(total)}</b></div></div>{error&&<p className="error">{error}</p>}<button className="checkout" onClick={checkout}>Place order · {money(total)}</button><small>By ordering, you confirm this table and item selection.</small></aside></div>}

function OrderTracking({order,back}:{order:any;back:()=>void}){const stages=['placed','accepted','preparing','ready','served'];return <div className="orderStatus professionalTracking"><div className="brand"><span>IK</span> Indian Kitchen</div><p className="eyebrow red">Order #{order.order_number}</p><h1>Your meal is<br/><em>{order.status==='placed'?'with the kitchen':order.status}.</em></h1><div className="steps">{stages.map((status,index)=><div className={stages.indexOf(order.status)>=index?'done':''} key={status}><i/>{status}</div>)}</div><div className="trackingSummary">{order.items.map((item:any)=><div key={item.id}><span>{item.quantity}× {item.item_name}</span><b>{money(item.line_total)}</b></div>)}<div><span>Total</span><b>{money(order.total)}</b></div></div><p>{order.payment_status==='paid'?'Payment received':order.payment_method==='cash'?'Please pay cash at the counter.':'Confirming payment…'}</p>{order.payment_status==='paid'&&<a className="primary" href={`${API}/api/invoices/${order.id}`}>Download invoice</a>}<button className="textBtn" onClick={back}>Back to menu</button></div>}
