'use client';

import { useState } from 'react';
import { BellRing, Check, ChefHat, Clock3, CreditCard, Eye, IndianRupee, MapPin, Phone, Receipt, StickyNote, User, X } from 'lucide-react';
import { money } from '@/lib/api';

const nextStatus:any={placed:'accepted',accepted:'preparing',preparing:'ready',ready:'served'};
const actionLabel:any={accepted:'Accept order',preparing:'Start preparing',ready:'Mark ready',served:'Mark served'};
const stages=['placed','accepted','preparing','ready','served'];

export default function ProfessionalOrderBoard({orders,active,role,update,paid,cancel}:{orders:any[];active:any[];role:string;update:(o:any,s:string)=>Promise<void>;paid:(id:string)=>Promise<void>;cancel?:(o:any,reason:string)=>Promise<void>}){
  const [selected,setSelected]=useState<any|null>(null);
  const [busy,setBusy]=useState<string|null>(null);
  async function act(key:string,job:()=>Promise<void>){if(busy)return;setBusy(key);try{await job()}finally{setBusy(null)}}
  return <><div className="stats"><article><Clock3/><span><b>{active.length}</b> Active orders</span></article><article><BellRing/><span><b>{active.filter(order=>order.status==='placed').length}</b> Awaiting action</span></article><article><IndianRupee/><span><b>{orders.filter(order=>order.payment_status==='paid').length}</b> Paid orders</span></article></div><div className="tickets">{orders.map(order=><article className={`ticket ${order.status}`} key={order.id}><div className="ticketHead"><div><p>ORDER #{order.order_number} Â· {formatTime(order.created_at)}</p><h3>{order.table_name}</h3></div><span>{order.status}</span></div><div className="ticketCustomer">{role!=='kitchen'&&<><User/><span>{order.customer_name||'Walk-in guest'}</span></>}<b>{order.items.reduce((sum:number,item:any)=>sum+item.quantity,0)} items</b></div><div className="ticketItems">{order.items.slice(0,4).map((item:any)=><div key={item.id}><b>{item.quantity}Ã—</b><span>{item.item_name}{item.special_instructions&&<small>{item.special_instructions}</small>}</span></div>)}{order.items.length>4&&<small className="moreItems">+{order.items.length-4} more items</small>}</div>{role!=='kitchen'&&<div className="ticketMeta"><span>{money(order.total)}</span><span className={order.payment_status}>{order.payment_method} Â· {order.payment_status}</span></div>}<div className="actions splitActions">{role!=='kitchen'&&<button className="viewOrder" onClick={()=>setSelected(order)}><Eye/> View details</button>}{role==='operator'&&order.payment_method==='cash'&&order.payment_status==='pending'&&<button disabled={!!busy} onClick={()=>act(`pay-${order.id}`,()=>paid(order.id))}>{busy===`pay-${order.id}`?'Savingâ€¦':'Cash received'}</button>}{role==='operator'&&order.status==='ready'&&<button disabled={!!busy} onClick={()=>act(order.id,()=>update(order,'served'))}>{busy===order.id?'Updatingâ€¦':'Mark served'}</button>}{(role==='admin'||(role==='operator'&&!['ready','served','cancelled'].includes(order.status)))&&cancel&&<button className="cancelOrder" disabled={!!busy} onClick={()=>{const reason=window.prompt('Cancellation reason (required)');if(reason?.trim())act(`cancel-${order.id}`,()=>cancel(order,reason))}}>Cancel</button>}{role==='admin'&&nextStatus[order.status]&&<button disabled={!!busy} onClick={()=>act(order.id,()=>update(order,nextStatus[order.status]))}>{busy===order.id?'Updatingâ€¦':actionLabel[nextStatus[order.status]]}</button>}</div></article>)}{!orders.length&&<div className="empty"><ChefHat/><h3>All caught up.</h3><p>New orders will appear here instantly.</p></div>}</div>{selected&&<OrderDetails order={orders.find(order=>order.id===selected.id)||selected} close={()=>setSelected(null)}/>}</>;
}

function OrderDetails({order,close}:{order:any;close:()=>void}){
  const currentIndex=stages.indexOf(order.status);
  return <div className="orderDrawer"><div className="orderDrawerBackdrop" onClick={close}/><aside><header><div><p>ORDER #{order.order_number}</p><h2>{order.table_name}</h2><span>{new Date(order.created_at).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})}</span></div><button onClick={close}><X/></button></header><div className="orderProgress">{stages.map((stage,index)=><div className={index<=currentIndex?'complete':''} key={stage}><i>{index<currentIndex?<Check/>:index+1}</i><span>{stage}</span></div>)}</div><section className="guestDetails"><div><User/><span>Guest<b>{order.customer_name||'Walk-in guest'}</b></span></div><div><Phone/><span>Phone<b>{order.customer_phone||'Not provided'}</b></span></div><div><MapPin/><span>Service<b>{order.table_name} Â· Dine-in</b></span></div><div><CreditCard/><span>Payment<b className={order.payment_status}>{order.payment_method} Â· {order.payment_status}</b></span></div></section>{order.notes&&<div className="orderNote"><StickyNote/><div><b>Order note</b><p>{order.notes}</p></div></div>}<section className="orderLines"><h3><Receipt/> Order items</h3>{order.items.map((item:any)=><div className="orderLine" key={item.id}><b>{item.quantity}Ã—</b><div><strong>{item.item_name}</strong>{item.special_instructions&&<small>â€œ{item.special_instructions}â€</small>}<span>{money(item.unit_price)} each</span></div><em>{money(item.line_total)}</em></div>)}</section><section className="orderTotals"><div><span>Subtotal</span><b>{money(order.subtotal)}</b></div><div><span>GST</span><b>{money(order.tax_amount)}</b></div><div className="grandTotal"><span>Total</span><b>{money(order.total)}</b></div></section><footer><span>Order ID</span><code>{order.id}</code></footer></aside></div>;
}

function formatTime(value:string){return new Date(value).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit'});}


